# Generated by Django 3.2.5 on 2021-08-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.TextField(max_length=200)),
                ('Preco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Ano', models.DateField()),
                ('Imagens', models.ImageField(upload_to='veiculosImg/%d/%m%Y')),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.marcas')),
            ],
        ),
    ]
