# Generated by Django 3.2.5 on 2021-08-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculos',
            name='Imagens',
        ),
        migrations.AlterField(
            model_name='marcas',
            name='Marca',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='Nome',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagens', models.ImageField(upload_to='veiculosImg/%d/%m%Y')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.veiculos')),
            ],
        ),
    ]
