# Generated by Django 3.2.5 on 2021-08-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20210801_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='Imagem',
            field=models.ImageField(default=1, upload_to='veiculosImg/%d/%m%Y'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='Marca',
            field=models.CharField(max_length=200),
        ),
    ]
