# Generated by Django 3.2.5 on 2021-08-03 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20210803_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='Marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.marcas'),
        ),
    ]
