# Generated by Django 3.2.5 on 2021-08-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_veiculos_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='Ano',
            field=models.DateField(verbose_name='%Y'),
        ),
    ]
