# Generated by Django 3.2.5 on 2021-08-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_veiculos_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='Ano',
            field=models.IntegerField(),
        ),
    ]
